name: Build data files
on:
  push:
    branches: [ main ]
    paths:
      - "projects/**"
      - "experience/**"
      - "scripts/build_data.py"
      - ".github/workflows/build-data.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml
      - run: python scripts/build_data.py
      - name: Commit data files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add assets/data/*.json
          git diff --staged --quiet || git commit -m "chore: update data files"
          git push
